blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    about: Open a GitHub discussion or a regular issue with the "question" label.
    url: https://github.com/Arjun-Aravind/moderato/discussions
